export const GAME_EVENTS = Object.freeze({
  GAME_STARTED: "GAME_STARTED",
  CARD_PLAYED: "CARD_PLAYED",
  CARD_DRAWN: "CARD_DRAWN",
  CREATURE_ATTACKED: "CREATURE_ATTACKED",
  PLAYER_DAMAGED: "PLAYER_DAMAGED",
  PLAYER_HEALED: "PLAYER_HEALED",
  MANA_CHANGED: "MANA_CHANGED",
  TURN_ENDED: "TURN_ENDED",
  GAME_OVER: "GAME_OVER",
  CHAT_MESSAGE_SENT: "CHAT_MESSAGE_SENT",
  CHAT_MESSAGE_RECEIVED: "CHAT_MESSAGE_RECEIVED",
  SOUND_REQUESTED: "SOUND_REQUESTED",
  HUD_UPDATED: "HUD_UPDATED",
});

